package com.alipay.zdal.test.ut.sqlparser.mysql;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;


@RunWith(Suite.class)
@Suite.SuiteClasses({ 
	ArithmeticOperatorsTest.class,AssignmentOperatorsTest.class,BitFunctionsTest.class,
	CALL_Test.class,CastFunctionsAndOperatorsTest.class,CommitTest.class,ComparisonFunctionsAndOperatorsTest.class,
	ControlFlowFunctionsTest.class,CreateUserTest.class,DateAndTimeFunctionsTest.class,
	DateAndTimeValuesTest.class,DeleteSyntaxTest.class,DropTableTest.class,DropUserTest.class,
	FullTextSearchesWithQueryExpansionTest.class,HexadecimalValuesTest.class,InformationFunctionsTest.class,
	InsertSyntaxTest.class,Kill_Test.class,LOAD_XML_Syntax_Test.class,LoadDataInFileSyntaxTest.class,
	LogicalOperatorsTest.class,MathematicalFunctionsTest.class,MiscellaneousFunctionsTest.class,
	MySqlCreateTableTest.class,MySqlCreateTableTest1.class,MySqlCreateTableTest2.class,MySqlCreateTableTest3.class,
	MySqlDeleteTest_0.class,MySqlDeleteTest_1.class,MySqlDeleteTest_2.class,MySqlDescribteTest.class,
	MySqlDropTableTest.class,MySqlParameterizedOutputVisitorTest.class,MySqlParameterizedOutputVisitorTest2.class,
	MySqlSchemaStatVisitorTest_Delete.class,MySqlSchemaStatVisitorTest_Insert.class,MySqlSchemaStatVisitorTest_Select_Limit.class,
	MySqlSchemaStatVisitorTest_Select_OrderBy.class,MySqlSchemaStatVisitorTest_Subquery.class,
	MySqlSchemaStatVisitorTest_Subquery2.class,MySqlSchemaStatVisitorTest_Update.class,
	MySqlSchemaStatVisitorTest1.class,MySqlSchemaStatVisitorTest2.class,MySqlSchemaStatVisitorTest3.class,
	MySqlSchemaStatVisitorTest5.class,MySqlSelectGroupTest.class,MySqlSelectLimitTest.class,
	MySqlSelectTest_1.class,MySqlSelectTest_2.class,MySqlSelectTest_3.class,MySqlSelectTest_4.class,
	MySqlSelectTest_5.class,MySqlSelectTest_6.class,MysqlSqlSelectTest_2.class,MySqlUpdateStatementLimitTest.class,
	NumberTest.class,RegularExpressionsTest.class,REPLACE_Syntax_Test.class,SELECT_Syntax_Test.class,
	SHOW_COLUMNS_Syntax_Test.class,SHOW_STATUS_Syntax_Test.class,SHOW_WARNINGS_Syntax_Test.class,
	SQLParserOfMysqlWithDeleteTest.class,SQLParserOfMysqlWithInsertTest.class,SQLParserOfMysqlWithSelectTest.class,
	SQLParserOfMysqlWithUpdateTest.class,SQLParserOfOracleWithDeleteTest.class,SQLParserOfOracleWithInsertTest.class,
	SQLParserOfOracleWithSelectTest.class,SQLParserOfOracleWithUpdateTest.class,SQLParserWithSelectInTest.class,
	SQLSelectTest.class,START_TRANSACTION_Test.class,StringComparisonFunctionsTest.class,TestSqlParser.class,
	Binlog_Test.class,HelpTest.class,MySqlAlterTableTest.class,MySqlAlterTableTest1.class,MySqlSelectTest_0.class,
	Reset_Test.class,SHOW_DATABASES_Syntax_Test.class,SQLParserTest.class,DMLInsertParserTest.class,DDLParserTest.class,
	LiteralHexadecimalTest.class,TestOnlineSQLTest3.class,SQLExprParserTest.class,OnlineSQLTest2.class,OnlineSQLTest.class,
	KeywordsMySqlTest.class,TestReplaceLicense.class
	
	
})

public class UtZdalSqlParserMysqlSuite {

	
}
