package com.alipay.zdal.parser.druid.bvt.sql.mysql;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses({
	ArithmeticOperatorsTest.class,
	AssignmentOperatorsTest.class,
	BitFunctionsTest.class,
	BooleanValuesTest.class,
	CALL_Test.class,
	CastFunctionsAndOperatorsTest.class,
	CommitTest.class,
	ComparisonFunctionsAndOperatorsTest.class,
	ControlFlowFunctionsTest.class,
	CreateUserTest.class,
	DateAndTimeFunctionsTest.class,
	DateAndTimeValuesTest.class,
	DeleteSyntaxTest.class,
	DropTableTest.class,
	DropUserTest.class,
	EncryptionAndCompressionFunctionsTest.class,
	FullTextSearchesWithQueryExpansionTest.class,
	HexadecimalValuesTest.class,
	InformationFunctionsTest.class,
	InsertSyntaxTest.class,
	Kill_Test.class,
	LOAD_XML_Syntax_Test.class,
	LoadDataInFileSyntaxTest.class,
	LogicalOperatorsTest.class,
	MathematicalFunctionsTest.class,
	MiscellaneousFunctionsTest.class,
	MySqlCreateTableTest.class,
	MySqlCreateTableTest1.class,
	MySqlCreateTableTest2.class,
	MySqlCreateTableTest3.class,
	MySqlDeleteTest_0.class,
	MySqlDeleteTest_1.class,
	MySqlDeleteTest_2.class,
	MySqlDescribteTest.class,
	MySqlDropTableTest.class,
	MySqlParameterizedOutputVisitorTest.class,
	MySqlParameterizedOutputVisitorTest2.class,
	MySqlSelectGroupTest.class,
	MySqlSelectLimitTest.class,
	MySqlSelectTest_0.class,
	MySqlSelectTest_1.class,
	MySqlSelectTest_2.class,
	MySqlSelectTest_3.class,
	MySqlSelectTest_4.class,
	MySqlSelectTest_5.class,
	MySqlSelectTest_6.class,
	MySqlUpdateStatementLimitTest.class,
	NumberTest.class,
	RegularExpressionsTest.class,
	REPLACE_Syntax_Test.class,
	Reset_Test.class,
	SELECT_Syntax_Test.class,
	SHOW_COLUMNS_Syntax_Test.class,
	SHOW_DATABASES_Syntax_Test.class,
	SHOW_STATUS_Syntax_Test.class,
	SHOW_TABLES_Syntax_Test.class,
	SHOW_WARNINGS_Syntax_Test.class,
	SQLParserTest.class,
	SQLSelectTest.class,
	START_TRANSACTION_Test.class,
	StringComparisonFunctionsTest.class,
	StringFunctionsTest.class,
	StringTest.class,
	XMLFunctionsTest.class
}
)
public class SuitTest2 {

}
